---

- name: Add official nginx GPG key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add offficial nginx repository
  lineinfile: >
    dest=/etc/apt/sources.list
    line='{{item}} http://nginx.org/packages/ubuntu/ {{ansible_distribution_release}} nginx'
  with_items:
    - deb
    - deb-src

- name: apt-get update
  apt: update_cache=yes

- name: install nginx
  apt: name=nginx state=latest
